### ISSUE TITLE
Use FIFO instead of echo

### ISSUE THREAD

**Issue by alexherbo2** [andreyorst/plug.kak#10]
Have a nice colored FIFO could be helpful to keep log.

Moreover, we could imagine some nice interactions on this buffer, like _Re-update_ or _Re-try_ by pressing <kbd>Return</kbd> on a given message.

It’s easy to implement and asynchronous by nature, so it could even simplify your implementation.

### Implementation examples

- [grep.kak](https://github.com/mawww/kakoune/blob/master/rc/core/grep.kak)
- [make.kak](https://github.com/mawww/kakoune/blob/master/rc/core/make.kak)
- [edit-directory.kak](https://github.com/alexherbo2/edit-directory.kak/blob/master/rc/edit-directory.kak)
- [filetree.kak](https://github.com/occivink/kakoune-filetree/blob/master/filetree.kak) (Waiting merge [#2](https://github.com/occivink/kakoune-filetree/pull/2))

**Comment by andreyorst** [comment]
I've tried to do it, but can't see the proper way of how I should parse output for each git process running in the background, and put it to the single buffer as sorted list of plugin-per-line-status.

I'm currently little busy with adding post-update `"do: ..."` *hooks* to rebuild [kak-lsp](https://github.com/ul/kak-lsp) for example, and I think that this feature is little more important right now, but thanks for the tips.

**Comment by andreyorst** [comment]
I think that I'll make it in relative simple way. Just log messages which plugin gets an update, which is installed. Maybe some time later it will evolve into interactive buffer with logs, errors, etc etc.

**Comment by andreyorst** [comment]
@alexherbo2 I want to show info about what's `plug.kak` is doing in `*plug*` buffer. For example, buffer is formatted like so:
```
andreyorst/plug.kak: Update available
delapouite/kakoune-text-objects: Up to date
occivink/kakoune-vertical-selection: Up to date
occivink/kakoune-gdb: Up to date
andreyorst/base16-gruvbox.kak: Update available
andreyorst/fzf.kak: Up to date
TeddyDD/kakoune-edit-or-dir: Up to date
ul/kak-lsp: Up to date
andreyorst/powerline.kak: Up to date
andreyorst/smarttab.kak: Up to date
alexherbo2/auto-pairs.kak: Up to date
alexherbo2/replace.kak: Up to date
alexherbo2/move-line.kak: Up to date
occivink/kakoune-snippets: Up to date
occivink/kakoune-find: Up to date
```

I want to execute `plug-update` and see how changes affect this fifo buffer. Should I just modify a fifo file with sed, or there's a better/proper way?

**Comment by alexherbo2** [comment]
I don’t understand, a FIFO is a named pipe, you can’t modify the file with `sed`.

**Comment by andreyorst** [comment]
I don't understand it either, how to update it then?

**Comment by andreyorst** [comment]
For example, i have two plugins in my config, but they're not installed. I call `plug-list` command and is opens a buffer `*plug*` with FIFO displayed in it with this contents:
```
ul/kak-lsp: Not installed
alexherbo2/move-line.kak: Not installed
```
Now I execute `plug-update`. I want this to be reflected in `*plug*` buffer like so:
```
ul/kak-lsp: Installing
alexherbo2/move-line.kak: Installing
```
After plugins are installed, post-install hooks are being run:
```
ul/kak-lsp: Running post-update hooks
alexherbo2/move-line.kak: Done
```
And after everything is done, `*plug*` buffer content is:
```
ul/kak-lsp: Done
alexherbo2/move-line.kak: Done
```

Can I achieve this with FIFO? I've already made an interactive `plug-list` and `plug-fifo-operate` commands, I just need to understand how to update it properly. I guess I can reconstruct it fully every time, but this would be performance impact.

**Comment by alexherbo2** [comment]
You can’t.

**Comment by alexherbo2** [comment]
``` kak
define-command update %{ evaluate-commands %sh{
  out=$(mktemp --directory)
  fifo=$out/fifo
  mkfifo $out/fifo
  ((
    for plugin in a/b c/d e/f g/h; do
      echo $plugin: Installing
      sleep 1
    done
    for plugin in a/b c/d e/f g/h; do
      echo $plugin: Running post-update hooks
      sleep 1
    done
    for plugin in a/b c/d e/f g/h; do
      echo $plugin: Done
      sleep 1
    done
  ) > $fifo) < /dev/null > /dev/null 2>&1 &
  echo "
    edit -fifo $fifo -scroll *update*
    hook -always -once buffer BufCloseFifo '' %(nop %sh(rm --recursive $out))
  "
}}
```

**Comment by alexherbo2** [comment]
# Options
declare-option str-list plugins P L U G I N S

# Faces
set-face global PlugPlugin attribute
set-face global PlugMessage string

# Highlighters
add-highlighter shared/plug group
add-highlighter shared/plug/ regex ^([^:]+):\h+([^\n]+)$ 1:PlugPlugin 2:PlugMessage

# File-type
hook global BufCreate \*plug\* %{
  set-option buffer filetype plug
}

hook -group plug-highlight global WinSetOption filetype=plug %{
  add-highlighter window/plug ref plug
  hook -always -once window WinSetOption filetype=.* %{
    remove-highlighter windows/plug
  }
}

# Update
define-command plug-update %{
  edit -scratch *plug*
  evaluate-commands -buffer *plug* -save-regs '"' %{
    set-register dquote %sh{
      eval "set -- $kak_opt_plugins"
      printf '%s: Processing\n' $@
    }
    execute-keys '%R'
  }
  nop %sh{ {
    message() {
      plugin=$1
      message=$2
      printf '
        evaluate-commands -buffer *plug* -save-regs %%("/) %%{
          set-register / %%(^%s: +)
          set-register %%(") %%(%s)
          execute-keys %%(/<ret>lGlR)
        }
      ' "$plugin" "$message" | kak -p $kak_session
      sleep 0.2
    }
    eval "set -- $kak_opt_plugins"
    index=0
    for plugin in $@; do
      message $plugin Installing
      if test $((index % 2)) = 0; then
        message $plugin 'Running post-update hooks'
      fi
      message $plugin Done
      index=$((index + 1))
    done
  } < /dev/null > /dev/null 2>&1 & }
}

**Comment by alexherbo2** [comment]
``` kak
# Options
declare-option str-list plugins P L U G I N S

# Faces
set-face global PlugPlugin attribute
set-face global PlugMessage string

# Highlighters
add-highlighter shared/plug group
add-highlighter shared/plug/ regex ^([^:]+):\h+([^\n]+)$ 1:PlugPlugin 2:PlugMessage

# File-type
hook global BufCreate \*plug\* %{
  set-option buffer filetype plug
}

hook -group plug-highlight global WinSetOption filetype=plug %{
  add-highlighter window/plug ref plug
  hook -always -once window WinSetOption filetype=.* %{
    remove-highlighter windows/plug
  }
}

# Update
define-command plug-update %{
  edit -scratch *plug*
  evaluate-commands -buffer *plug* -save-regs '"' %{
    set-register dquote %sh{
      eval "set -- $kak_opt_plugins"
      printf '%s: Processing\n' $@
    }
    execute-keys '%R'
  }
  nop %sh{ {
    message() {
      plugin=$1
      message=$2
      printf '
        evaluate-commands -buffer *plug* -save-regs %%("/) %%{
          set-register / %%(^%s: +)
          set-register %%(") %%(%s)
          execute-keys %%(/<ret>lGlR)
        }
      ' "$plugin" "$message" | kak -p $kak_session
      sleep 0.2
    }
    eval "set -- $kak_opt_plugins"
    index=0
    for plugin in $@; do
      message $plugin Installing
      if test $((index % 2)) = 0; then
        message $plugin 'Running post-update hooks'
      fi
      message $plugin Done
      index=$((index + 1))
    done
  } < /dev/null > /dev/null 2>&1 & }
}
```

**Comment by alexherbo2** [comment]
``` kak
# Options
declare-option str-list plugins P L U G I N S

# Faces
set-face global PlugPlugin attribute
set-face global PlugMessage string

# Highlighters
add-highlighter shared/plug group
add-highlighter shared/plug/message regex ^([^:]+):\h+([^\n]+)$ 1:PlugPlugin 2:PlugMessage

# File-type
hook global BufCreate \Q*plug* %{
  set-option buffer filetype plug
}

hook -group plug-highlight global WinSetOption filetype=plug %{
  add-highlighter window/plug ref plug
  hook -always -once window WinSetOption filetype=.* %{
    remove-highlighter window/plug
  }
}

# Update
define-command plug-update %{
  edit -scratch *plug*
  evaluate-commands -buffer *plug* -save-regs '"' %{
    set-register dquote %sh{
      eval "set -- $kak_opt_plugins"
      printf '%s: Processing\n' $@
    }
    execute-keys '%R'
  }
  nop %sh{ {
    message() {
      plugin=$1
      message=$2
      printf '
        evaluate-commands -buffer *plug* -save-regs "/""" %%{
          set-register / %%(^%s:\\h+)
          set-register dquote %%(%s)
          execute-keys /<ret>lGlR
        }
      ' "$plugin" "$message" | kak -p $kak_session
      sleep 0.2
    }
    eval "set -- $kak_opt_plugins"
    index=0
    for plugin in $@; do
      message $plugin Installing
      if test $((index % 2)) = 0; then
        message $plugin 'Running post-update hooks'
      fi
      message $plugin Done
      index=$((index + 1))
    done
  } < /dev/null > /dev/null 2>&1 & }
}
```

**Comment by andreyorst** [comment]
Nice
![vaiv](https://user-images.githubusercontent.com/19470159/51083546-2009ef80-172d-11e9-923c-c8f8c3ceaf72.gif)
