### ISSUE TITLE
plug theme

### ISSUE THREAD

**Issue by mralusw** [andreyorst/plug.kak#109]
For theme plugins, do we need to symlink every `.kak` file separately into `.kak/colors`? It seems symlinking the plugin folder directly works fine. Benefits:
- avoids conflicts for identically-named `.kak` files from different themes
- should be more manageable for users: with tens of `.kak` links for some themes, it's hard to tell where each colorscheme comes from (and also hard to figure out which theme plugins are active)
- simplifies `plug()` logic and speeds it up (no `find`, single `ln`)

**Comment by mralusw** [comment]
Well, I've pushed the directory-symlink change, as well as the `.git` double-stripping (#111) to the existing PR (#110)

Installing directly into `colors` sounds nice, but seems quite dangerous, as we don't currently store `plug` invocation parameters after parsing, only URLs (see #113)

**Comment by andreyorst** [comment]
This was fixed in 0074c8c512e0e60d5523894a9d8b88b264da8495. Thanks, @mralusw
