### ISSUE TITLE
double .git stripping

### ISSUE THREAD

**Issue by mralusw** [andreyorst/plug.kak#111]
It seems `plug()` strips `.git` extensions from URLs, then (with `ensure`) calls `plug_install`, which strips another `.git`. Also, `plug` strips a final `/`, but `plug_install` doesn't.

Apart from the `plug ensure` scenario, `plug_install` can of course also be called directly or, from `plug_fifo_operate`; in these cases it receives an unstripped URL.

For consistency, perhaps
- `plug()` should save the original URL before stripping and, with `ensure`, feed `plug_install` that original URL
- `plug_install()` should also strip `/`, just like `plug()` &mdash; otherwise `http://.../` remain impossible to install

What do you think?

**Comment by andreyorst** [comment]
This was fixed in 6c9818b76a732bc3fd10bdf2692d14ca25e6e478. Thanks @mralusw
