### ISSUE TITLE
git URLs for private repos

### ISSUE THREAD

**Issue by mralusw** [andreyorst/plug.kak#119]
It looks like one can only use `git@host:PATH` URLs, not `user@host:PATH` (nor, for that matter, `[git+]ssh://user@host:port/PATH`, useful since SSH should at least run on a different port for a private host; this can, however, be emulated via `~/.ssh/config`)

At least the `git@host:` form should be relaxed to `user@host:`

**Comment by andreyorst** [comment]
I've relaxed this part to `*@*`. Please test (if this is still relevant)
