### ISSUE TITLE
download plugins to subdirectories

### ISSUE THREAD

**Issue by TeddyDD** [andreyorst/plug.kak#14]
Currently `plugins` directory is quite messy, I propose that plug should install plugins to
`author/repo` or even `hosting/author/repo` subdirectories.

Not sure if this make things much more complex, maybe it's not worth it. WDYT?

**Comment by andreyorst** [comment]
I don't think that this is necessary, since ideally user should never bother about plugin installation directory. At least I was never bothered about contents of my `bundle` directory managed by vundle and vim-plug.

Although it can benefit when you want to manually update/clean plugin, since shell candidates will be more orginized, but I suspect that fuzzy matching still more useful here.

**Comment by TeddyDD** [comment]
I'm concerned with plugins I wrote and I manage with plug, I couldn't find them :laughing:

**Comment by andreyorst** [comment]
Sorry, I don't understand it. Can you please bring more details?

**Comment by TeddyDD** [comment]
I mean, I manage my personal plugins with plug.kak, and when I want to edit them I need to dig through plugins directory :wink: 

It's not really an issue, more like suggestion, I don't have strong opinion on that.

**Comment by andreyorst** [comment]
Ah, got it. I'll try to do this, but I'd like to try to solve #10 first

**Comment by andreyorst** [comment]
I've thought about it a lot, and I don't think that this will be good idea to do. Basically rightnow I manage only one directory and names of all dirs with plugins. If I implement this I'll need to manage installation directory and, directories named against username, and subdirectories, which makes it harder to cycle through when updating and when loading plugins.

I'm closing this for now

**Comment by andreyorst** [comment]
This can be useful though. If for example there are two plugins with the same name but by the different authors plug will be confused (I've encountered this situation)
