### ISSUE TITLE
Can't set `noload` and `(branch|tag|commit)` options simultaneously 

### ISSUE THREAD

**Issue by evanrelf** [andreyorst/plug.kak#24]
This works without any errors:

```
plug 'andreyorst/plug.kak' noload
```

However, this gives me an error:

```
plug 'andreyorst/plug.kak' 'branch: v2018.10.27' noload
```

```
~/.config/kak/plugins.kak:3:54: 'plug' 3:57: 'evaluate-commands' 2:66: 'plug-configure' 1:2: 'evaluate-commands' no such command: 'noload'
/Users/evanrelf/.config/kak/kakrc:1:1: 'source' 3:54: 'plug' 3:57: 'evaluate-commands' 2:66: 'plug-configure' 1:2: 'evaluate-commands' no such command: 'noload'
/usr/local/Cellar/kakoune/2018.10.27/share/kak/kakrc:5:853: 'evaluate-commands' 97:20157: 'source' 1:1: 'source' 3:54: 'plug' 3:57: 'evaluate-commands' 2:66: 'plug-configure' 1:2: 'evaluate-commands' no such command: 'noload'
error while parsing kakrc:
    1:1: 'source' 5:853: 'evaluate-commands' 97:20157: 'source' 1:1: 'source' 3:54: 'plug' 3:57: 'evaluate-commands' 2:66: 'plug-configure' 1:2: 'evaluate-commands' no such command: 'noload'
```

I'm using [kak-lsp](https://github.com/ul/kak-lsp) with a `noload` parameter and it works fine; it's only when I try to combine `noload` and a `(branch|tag|commit)` parameter that it gives that error.

Tested on the latest commit ([b3801d2](https://github.com/andreyorst/plug.kak/commit/b3801d299ea5037c30f8a7a459cab77d9b5b06e8)) and one before that ([98defec](https://github.com/andreyorst/plug.kak/commit/98defecbb6e9f203f5922d0030816ffc8eaafe3b)); both had this problem.

**Comment by andreyorst** [comment]
Unfortunately **plug.kak** can't change it's own branch since it must be loaded to change it, and after changing it old loaded branch of **plug.kak** is used still, therefore Kakoune needs a restart. I suggest to swith branch manually for **plug.kak** and treat it as part of its installation process.

I'll investigate the problem with combining these two attributes.

**Comment by evanrelf** [comment]
That makes sense

**Comment by andreyorst** [comment]
Also `v2018.10.28` is the default branch. You don't need to specify it explicitly with `"branch:" command

**Comment by evanrelf** [comment]
Yeah I’ll test it when I get a chance

**Comment by evanrelf** [comment]
It works!
