### ISSUE TITLE
`awk: illegal field $(), name "F"`

### ISSUE THREAD

**Issue by evanrelf** [andreyorst/plug.kak#25]
From `*debug*` buffer, after running `plug-install`:

```
awk: illegal field $(), name "F"
 input record number 1, file 
 source line number 1
```

I never get the `Done installing plugins` message, it just hangs on `Installing plugins in background`.

It seems the problem appeared in the latest commit ([b3801d2](https://github.com/andreyorst/plug.kak/commit/b3801d299ea5037c30f8a7a459cab77d9b5b06e8)). I can run `plug-install` with no problems on the previous commit ([98defec](https://github.com/andreyorst/plug.kak/commit/98defecbb6e9f203f5922d0030816ffc8eaafe3b)).

My guess is that my version of `awk` on macOS is different from whatever version you're using on Linux (I have version `20070501` of `awk` installed on macOS 10.14 Mojave).

**Comment by andreyorst** [comment]
I've thought that `awk` is more portable. Can you please try to find a proper command for `awk` that will count `/` in the string and print it in the format of `number_of_slashes the_string`. Also if something like GNU awk is available can you please test it too? I have no macOS to test it, sorry.

```bash
find . -type f -name "*.kak" | awk -F/ '{print NF-1, $F}' | sort -n | cut -d' ' -f2
```
Basically this helps to sort output by printing the less nested files first.

**Comment by evanrelf** [comment]
Installing GNU Awk (version `4.2.1`) from Homebrew (`brew install gawk`) made the `awk` errors go away, and it seems like `plug-install` worked because my plugins are working, but the `Done installing plugins` message never appeared.

I can try experimenting more later today.

**Comment by andreyorst** [comment]
Great. I'll fix this in a munite.

**Comment by andreyorst** [comment]
Should be working now.

**Comment by evanrelf** [comment]
> I've removed the message, because it was showing irrelevant info about plug state if some hooks were running in background.

I hope in the future you add some indicator that plugins were installed successfully. Having the "done" message is reassuring that everything finished.

Is it possible to do something like `kak -e 'plug-update; quit'` to update plugins as part of an update script? I've been using `nvim +PlugClean! +PlugUpgrade +"PlugUpdate --sync" +qa` in my update script to update Vim plugins, and I wonder if it's possible to replicate in Kakoune.

**Comment by andreyorst** [comment]
> I hope in the future you add some indicator that plugins were installed successfully

#10 

Basically in current state this message was shown after the download process of every plugin is done, and pkst-install hooks were ignored. I've decided to disable it, because I've encountered a situation where Ive downloaded plugon and exited Kakoune before it finished building. This needs to be reworked.

 >Is it possible to do something like `kak -e 'plug-clean; plug-update; quit'` to update plugins as part of an update script? I've been using `nvim +PlugClean! +PlugUpgrade +"PlugUpdate --sync" +qa` in my update script to update Vim plugins, and I wonder if it's possible to replicate in Kakoune

Let's have a separate Issue for this?

**Comment by evanrelf** [comment]
I was just curious, but we can move it to a new issue if it’s a feature you’re open to.
