### ISSUE TITLE
`disable` option?

### ISSUE THREAD

**Issue by dpc** [andreyorst/plug.kak#31]
Sometimes there's a need to disable a plugin (during `kakrc` debugging, testing or because it misbehaves). It would be nice to have a keyword that would just make `plug.kak` skip a given plugin, and options associated with it.

**Comment by Delapouite** [comment]
Hello. You can prefix the line with `nop` as described here:
https://github.com/andreyorst/plug.kak/issues/5#issuecomment-430142412

**Comment by dpc** [comment]
Really? And it will have no other side-effects etc.?

**Comment by andreyorst** [comment]
No. There's no side effects. I was surprised too :smiley:

**Comment by dpc** [comment]
I am unable to re-open, but I don't think `nop` is what I want. It seems to me that some stuff is being evaluated.
From: https://github.com/mawww/kakoune

> nop: does nothing, but as with every other commands, arguments may be evaluated. S

Right now I have a borked `kak-lsp` plugin, and it is somehow causing my kakoune to be terribly slow. So I wanted to put disable it, so I can at least keep working. But after adding `nop` prefix the slowness is still there. After I actually commented out the whole section, the slowness is gone. **So `nop` is NOT the same as disabling the whole plugin** . It seems to me, it only prevents kakoune from interpreting output of a command.

**Comment by andreyorst** [comment]
> It seems to me, it only prevents kakoune from interpreting output of a command.

That should be enough to disable the plugin. I can add `disable` option for sure, but I'd like to see what errors do you get.

**Comment by dpc** [comment]
@andreyorst Yes. It was #37, maybe with a combination with something else. My kak-lsp section was somehow broken, and it was causing kak to choke on some IO (to kak-lsp server, I'm guessing?). Prefixing with `nop` did not changed that fact.

Errors were like this https://github.com/ul/kak-lsp/issues/153#issuecomment-452129965, though I might check again tomorrow, after I get access too my office laptop setup again. I've just figured out the correct config on my desktop, but here I was not experiencing the slowness after `:plug-update` (though everything stopped working too).
