### ISSUE TITLE
fd support?

### ISSUE THREAD

**Issue by vbauerster** [andreyorst/plug.kak#4]
Can you please add [fd](https://github.com/sharkdp/fd) support?
When I set `set-option global fzf_file_command 'fd --type f --follow'`, I got following:
[![Screen_Shot_2018-09-28_at_22.51.09.png](https://i.postimg.cc/bY35T4ZQ/Screen_Shot_2018-09-28_at_22.51.09.png)](https://postimg.cc/8sfwkKB5)

I suppose there should be info box message, instead of that line.

**Comment by vbauerster** [comment]
Sorry, this one is for fzf.kak. Closing :)

**Comment by andreyorst** [comment]
![image](https://user-images.githubusercontent.com/19470159/46230956-e5916800-c372-11e8-9cf0-5a90243027c3.png)
You fast! :)
