### ISSUE TITLE
plug_install_dir only accepts full paths

### ISSUE THREAD

**Issue by EmmChriss** [andreyorst/plug.kak#44]
My kakrc previously contained this exact line:
```
set-option global plug_install_dir '$HOME/.cache/kakoune_plugins'
```
I spent a couple hours trying to figure out why my plugins weren't installing, and what I found is that the above no longer works.
Instead, something like this, with a full path works:
```
set global plug_install_dir %sh{ echo "$HOME/.cache/kakoune_plugins" }
```
The documentation clearly states, that the former is functional, so that should be changed.

**Comment by andreyorst** [comment]
Ah, sorry for that, I didn't expect such error. Previously I've used `eval` everywhere, but after reading about that it potentially insecure I've decided to remove it, but forgot to update the documentation. The second example is the proper way of setting a path.
