### ISSUE TITLE
Allow to pass configuration to plug

### ISSUE THREAD

**Issue by alexherbo2** [andreyorst/plug.kak#5]
Continuing from https://github.com/alexherbo2/auto-pairs.kak/issues/16#issuecomment-429896027:

``` kak
plug alexherbo2/auto-pairs.kak %{
  hook global WinCreate .* auto-pairs-enable
  map global user s -docstring 'Surround' ':<space>auto-pairs-surround<ret>'
}
```

**Comment by andreyorst** [comment]
Yeah, I've thought about it, and actually doing implementation of it right now.

**Comment by andreyorst** [comment]
@alexherbo2 I've pushed the changes to the [Kakoune_dev](https://github.com/andreyorst/plug.kak/tree/Kakoune_dev) branch. I'll likely backport it to master if it is working fine. I've tested it with these configurations:
```sh
plug "andreyorst/fzf.kak" %{
	map -docstring 'fzf mode' global normal '<c-p>' ': fzf-mode<ret>'
	set-option global fzf_preview_width '65%'
	evaluate-commands %sh{
		if [ ! -z "$(command -v fd)" ]; then
			echo "set-option global fzf_file_command 'fd . --no-ignore --type f --follow --hidden --exclude .git --exclude .svn'"
		else
			echo "set-option global fzf_file_command \"find . \( -path '*/.svn*' -o -path '*/.git*' \) -prune -o -type f -follow -print\""
		fi
		if [ ! -z "$(command -v bat)" ]; then
			echo "set-option global fzf_highlighter 'bat'"
		elif [ ! -z "$(command -v highlight)" ]; then
			echo "set-option global fzf_highlighter 'highlight'"
		fi
	}
}

# automatic pair insertion and surroundig
plug "alexherbo2/auto-pairs.kak" %{
	hook global WinCreate .* %{ auto-pairs-enable }
	map global user -docstring 'surround selection' 's' ': auto-pairs-surround<ret>'
}
```

The downside of this method is that you can't just comment the `plug` line to not to load the plugin, but need to comment all the lines, which was not the case of initial implementation. I'm thinking about adding some sort of `plug-config "plugin" "configurations"` for such purposes, but I'm not sure if it is necessary.

**Comment by alexherbo2** [comment]
You can prefix the command with a `nop`.

**Comment by andreyorst** [comment]
What command?

**Comment by alexherbo2** [comment]
``` kak
nop plug alexherbo2/auto-pairs.kak %{
  …
}
```

**Comment by andreyorst** [comment]
Ah, got it. Nice idea
