### ISSUE TITLE
Spring Refactoring

### ISSUE THREAD

**Issue by andreyorst** [andreyorst/plug.kak#54]
Spring is coming, so I've decided to show some love to the code. I'm going to do bit of refactoring, some optimizations for performance hungry places, and simplify overall structure a bit. The plugin will act the same as before, but hopefully will be a bit faster on loading plugins and their configurations, and easier to maintain.

**Comment by andreyorst** [comment]
If anyone has ideas on code simplification/reorganisation I;ll be glad to hear them. You can browse current plugin state in [spring-refactoring](https://github.com/andreyorst/plug.kak/tree/spring-refactoring) branch.

**Comment by andreyorst** [comment]
the most performance hungry place is the second `for` here.
```sh
IFS='
'
set -f # set noglob
for file in "$2"; do
    file=$(printf "%s\n" "${file}" | sed 's/^\s\+//;s/\s\+$//')  # trim leading and trailing whitespaces
    for script in $(find -L ${kak_opt_plug_install_dir}/${plugin_dir} -type f -name "${file}" | awk -F/ '{ print NF-1, $0 }' | sort -n | cut -d' ' -f2); do
        printf "source '%s'\n" ${script}
    done
done
```
It waits for `find` to finish, and it is a *long* find, because we need to sort it's output by the depth, which is done with `awk`, `sort` and `cut`. This is needed because I've decided, that if plugin defines submodules those should be nested to a directory like so:
```
pluin
├── rc
│   ├── plugin.kak
│   └── submodule
│       └── submodule.kak
└── README.md
```
So each module that requires code in previous module it should be deeper in the file structure.

If we pass `*.kak` to this find command it will first form the list of files looking like so:
```
rc/plugin.kak
rc/submodule/submodule.kak
```
And `for` loop will iterate over them in right order.

I'm not sure how to optimize this place, as find doesn't support ordering, and we can't use it's `-exec` for this task.

**Comment by andreyorst** [comment]
there's another way to get sorted directories without `awk` but for some reason it is slower:
```sh
find . -printf "%d %p\n"| sort -n | cut -d ' ' -f 2
```

**Comment by andreyorst** [comment]
I've got rid of the second `for` loop in the [example](https://github.com/andreyorst/plug.kak/issues/54#issuecomment-468411288) above, but there's still too much going on:
```
find -L ${kak_opt_plug_install_dir}/${plugin_name} -path '*/.git*' -prune -o -type f -name "${file}" -printf "%d %p\n" | sort -n | awk '{ print "source \"" $2 "\""}'
```
I'd like to do faster sorting by depth here, so maybe whole part starting with `-printf` to the end should be replaced by `awk` or `perl`

**Comment by andreyorst** [comment]
If anyone knows how to implement sort -n within `awk`, it will be great addition,

**Comment by andreyorst** [comment]
So, I've reimplemented sorting part in Perl, but It seems that it doesn't work much faster, compared to composite `awk | sort | awk` method:
```perl
@sorted = map  { $_->[0] }
          sort { $a->[1] <=> $b->[1] }
          map  { [$_, ($_ =~ s/\//\//g)] }
               <>;
chomp(@sorted);
for(@sorted) {
    print "source \"", $_, "\"\n"
}
```
I've won around `0.03` seconds here, and loading 18 plugins is now something around `0.345827861`.

I wonder if there's a way to insert text directly to array while sorting.

**Comment by andreyorst** [comment]
post-update hooks seems to be broken now

**Comment by shumvgolove** [comment]
Came here to say thank you for your work. Kakoune is great replacement for neovim and seeing that someone cares to make Kakoune is even greater makes me happy.

**Comment by andreyorst** [comment]
Oh, I'm glad that this makes you happier! Thanks to you, when I hear that someone actually uses what I do, makes me more motivated.
