### ISSUE TITLE
Latest kakoune-git fails to load (487cb067ccf0e)

### ISSUE THREAD

**Issue by Crote** [andreyorst/plug.kak#55]
Plug started failing to load after an update with a highlighter error, one commit earlier works fine.

It seems like the highlighter group has not been defined?

**Comment by andreyorst** [comment]
Hm. Works fine for me. Can I observe your configuration somewhere?

Basically I've changed `window` highlighter to `shared` highlighter, and used existing `shared/kakrc` group.

**Comment by Crote** [comment]
I think I've figured out what's going on.

My `kakrc` is at https://gitlab.com/Crote/dotfiles/blob/master/kak/kakrc . I'm using https://github.com/Crote/kakoune-system-loader to autoload a subset of Kakoune's default scripts, but that's installed with Plug. So Plug requires the default `rc/core/kakrc.kak`, but that's not yet loaded, because Plug has not loaded my plugins yet...

**Comment by andreyorst** [comment]
Hm. That's interesting situation.
So the base-level configuration files are loaded by a plugin, which in turn is loaded by a plugin manager, which in turn uses base-level configuration files. I can use try block to add highlighters in case that `kakrc.kak` wasn't loaded but I'm not sure if this is a proper way to do it.

**Comment by andreyorst** [comment]
@Crote can you try `sprint-refactoring` branch?

**Comment by andreyorst** [comment]
Also, while reading your `kakrc` I've noticed this comment:

> \# This command will fail after a fresh installation. To fix this, run
> \#   git clone --branch kakoune-git https://github.com/andreyorst/plug.kak.git ~/my/dotfiles/kak/plugins/
> \# Afterwards, start Kakoune and install all plugins using
> \#   plug-install

You can set `plug_always_ensure` option to `true` and plug.kak will automatically install new plugins on Kakoune launch.

**Comment by Crote** [comment]
I can confirm that `spring-refactoring` @ b3c0a26be3d61d63c7f89c17d56b9b310233ee5c works fine, so I'm closing this.

Thanks for your config suggestions, they are indeed quite helpful! Perhaps something for the README?

**Comment by andreyorst** [comment]
I don't really want to maintain automatic installation of plug, because there variable options for everyone where to install plug.kak, where to install plugins, e.t.c. This one is pretty much rock solid and may not apply for everyone. Making it for everyone would make it complex. I think that instruction in readme is enough.
