### ISSUE TITLE
Syntax error when sourcing plug.kak

### ISSUE THREAD

**Issue by benburk** [andreyorst/plug.kak#60]
Just installed Kakoune and trying to set up plug.kak. My kakrc is empty. I've ran

```
mkdir -p ~/.config/kak/plugins/
git clone https://github.com/andreyorst/plug.kak.git ~/.config/kak/plugins/plug.kak
```

successfully, but when I try to run

```
source "~/.config/kak/plugins/plug.kak/rc/plug.kak"
```

I get the error:

```
plug.kak: line 56: syntax error near unexpected token `newline'
plug.kak: line 56: `try %<'
```

Fish is my default shell, and I tried running it in a bash shell as well. Not sure if that matters.

**Comment by andreyorst** [comment]
What's your environment? what Kakoune version?  Where does your sh executable is pointing to?

**Comment by andreyorst** [comment]
> Fish is my default shell

Kakoune doesn't work with fish, because it is not POSIX compliant shell.

> `source "~/.config/kak/plugins/plug.kak/rc/plug.kak"`

You've run this command inside kakoune, right? Not from the shell, right? You need to place this line in your kakrc, or other config file.

**Comment by benburk** [comment]
> You've run this command inside kakoune, right?

Aha! I was trying to run it in bash. It wasn't clear to me that source was also a kakoune command (since I just installed it). This solved my issue.

> Kakoune doesn't work with fish, because it is not POSIX compliant shell.

I have bash installed, but fish is my default shell. Do you see this being an issue down the road? In what way?

**Comment by andreyorst** [comment]
>I have bash installed, but fish is my default shell. Do you see this being an issue down the road? In what way?

@benburk Kakoune uses `sh` as shell to execute scripts. Which by default is a symbolic link to `bash` on most distributions, so you should be fine. However, it would be better to use `dash` because it is much faster than `bash` which makes Kakoune more performant. You can use environment variable `KAKOUNE_POSIX_SHELL` to make Kakoune use `dash` instead of `sh`

> Perhaps mentioning that in the readme would be helpful.

Yeah, I'll add this.
