### ISSUE TITLE
plug.kak: Can't declare highlighters for kakrc.

### ISSUE THREAD

**Issue by mogenson** [andreyorst/plug.kak#62]
New error message in the debug buffer as of Kakoune commit [92972bed](https://github.com/mawww/kakoune/commit/92972bed4fb4ff6dffd32169bc437de34acac6a9) and plug.kak commit 6076e4c:

```
plug.kak: Can't declare highlighters for kakrc.
          Detailed error: 2:6: 'add-highlighter' no such id: 'kakrc'
```

**Comment by andreyorst** [comment]
you need to use `dev` brunch

**Comment by mogenson** [comment]
Thanks.
