### ISSUE TITLE
Fails to load with latest master: 'define-command' unknown option '-shell-script-candidates'

### ISSUE THREAD

**Issue by haarts** [andreyorst/plug.kak#63]
Installing plug.kak as described in the README gets me this error on start-up:
```
/home/<sanitized>/.config/kak/plugins/plug.kak/rc/plug.kak:70:4171: 'define-command' unknown option '-shell-script-candidates'
/home/<sanitized>/.config/kak/kakrc:2:48: 'source' 70:4171: 'define-command' unknown option '-shell-script-candidates'
/home/<sanitized>/.local/share/kak/kakrc:5:846: 'evaluate-commands' 99:16501: 'source' 2:48: 'source' 70:4171: 'define-command' unknown option '-shell-script-candidates'
error while parsing kakrc:
    1:1: 'source' 5:846: 'evaluate-commands' 99:16501: 'source' 2:48: 'source' 70:4171: 'define-command' unknown option '-shell-script-candidates'
```

Kakoune version (master) 983a8f759a3a959c7712891e2180ab5357c139d2
plug.kak version 7a41cdff777f6d46b70f53833d37d3e6343efaa9

My kakrc contains only one line:
```
source "%val{config}/plugins/plug.kak/rc/plug.kak"
```

There are two things which strike me as odd. Line 70 of `plug.kak` does not contain `define-command`. And second the `-shell-script-candidates` isn't new. It was added late 2018.

**Comment by andreyorst** [comment]
> There are two things which strike me as odd. Line 70 of `plug.kak` does not contain `define-command`

https://github.com/andreyorst/plug.kak/blob/7a41cdff777f6d46b70f53833d37d3e6343efaa9/rc/plug.kak#L92-L94

> Kakoune version (master) 983a8f759a3a959c7712891e2180ab5357c139d2
plug.kak version 7a41cdf

It seems that I have different master hash:

    $ git rev-parse master 
    2bef1f1eb8314de610e0922c91d3df98152a7bb2

Bu still, if you're using Kakoune from master you need to use `dev` branch of plug.kak

**Comment by haarts** [comment]
> It seems that I have different master hash:
That was it! I was tracking a different remote in my Kakoune source clone. So obvious... Thanks!
