### ISSUE TITLE
Theme post-update hook fails on macOS

### ISSUE THREAD

**Issue by evanrelf** [andreyorst/plug.kak#66]
The `find` command here is what's failing:

https://github.com/andreyorst/plug.kak/blob/7a41cdff777f6d46b70f53833d37d3e6343efaa9/rc/plug.kak#L133

Changing `find -type f ...` to `find . -type f ...` seems to fix this on macOS.

**Comment by andreyorst** [comment]
bsd find... While I understand that this dot makes sense, but still, seriously why didn't they made it optional?

**Comment by evanrelf** [comment]
I think the optional path is a GNU find feature. Looks like POSIX find requires a path.

https://www.unix.com/man-page/posix/1p/find/

While I like how Kakoune defers to the shell for scripting, it's annoying having to worry about the idiosyncrasies of each OS you expect to run on...

**Comment by andreyorst** [comment]
> While I like how Kakoune defers to the shell for scripting, it's annoying having to worry about the idiosyncrasies of each OS you expect to run on...

Well, that's how software works. Even apps on JVM not truly cross platform sometimes.

> I think the optional path is a GNU find feature. Looks like POSIX find requires a path.

Yeah, I know. And other `find` usages in plug.kak are using path and respect the POSIX format. Theme post hooks were added long after that, and I simply forgot about it, so that's my bad.
