### ISSUE TITLE
plug-list shortcuts do nothing

### ISSUE THREAD

**Issue by TeddyDD** [andreyorst/plug.kak#68]
Kakoune v2019.07.01
2691c61b7c1ec9cf972fcc0ba2aa9fdd34dae9ca

As in description: calling `:plug-list` and using <kbd>U</kbd>, <kbd>I</kbd>, , <kbd>D</kbd>, <kbd>L</kbd> has no effect.

There is no logs/errors in `*debug*`

**Comment by andreyorst** [comment]
ohhohoh

I'll look into this tomorrow

**Comment by TeddyDD** [comment]
No hurry :)
