### ISSUE TITLE
Error while sourcing cannot find module kak

### ISSUE THREAD

**Issue by NikosEfthias** [andreyorst/plug.kak#69]
I am pretty new to kakoune editor but im a regular vim user. I am trying to source plug.kak in my kakrc file but i get the error message saying 
![image](https://user-images.githubusercontent.com/9097437/62520342-10bbd200-b836-11e9-9f2c-c2df61b23e2c.png)

**Comment by andreyorst** [comment]
It seems that you're using `autoload` directory, which causes Kakoune to skip loading of system configuration scripts

**Comment by NikosEfthias** [comment]
seems its working now thanks

**Comment by andreyorst** [comment]
great. With plug.kak you don't really need `autoload`. Can I close this?

**Comment by NikosEfthias** [comment]
sure,Thanks for the help

**Comment by Luflosi** [comment]
I had the same problem and was also using the autoload directory because the `README.md` suggested it:
> You can either symlink plug.kak file to your autoload directory, or use Kakoune source command.

Should the documentation be changed since this doesn't seem to work properly?

**Comment by andreyorst** [comment]
this should work properly, unless kakoune is loading files in different order from autoload and sources kakrc.kak after plug.kak. I guess I van declare highlighters in a hook

**Comment by irevoire** [comment]
Hello,
I have the same error but this time I don’t even have the autoload directory. Here is the full *debug* buffer:
```
/Users/irevoire/.config/kak/plugins/plug.kak/rc/plug.kak:no such command: 'require-module'
/Users/irevoire/.config/kak/kakrc:24:988: 'source' no such command: 'require-module'
/usr/local/Cellar/kakoune/2019.01.20/share/kak/kakrc:5:853: 'evaluate-commands' 98:20377: 'source' 24:988: 'source' no such command: 'require-module'
error while parsing kakrc:
    1:1: 'source' 5:853: 'evaluate-commands' 98:20377: 'source' 24:988: 'source' no such command: 'require-module'
```

If I delete all the following lines I can source the `plug.kak` but obviously the highlighting is broken and I guess if one day I try to update plug it’ll fail :(
https://github.com/andreyorst/plug.kak/blob/master/rc/plug.kak#L64-L87

**Comment by andreyorst** [comment]
If there's no such command `require-module` you need to update Kakoune

**Comment by Narven** [comment]
Hi, I know this is closed, but...

I'm having the same issue... at least the same result but the error is different.

`1:1: 'source' no such command: 'require-module'`

Could this be because im using `zsh` for the shell? Or I'm I missing some other tool?

I also used linuxbrew to install Kakoune, dont know if that affects it.

Im using Kakoune v2019.01.20 on Linux Mint

Thanks

**Comment by Narven** [comment]
> If there's no such command `require-module` you need to update Kakoune

I have the latest version, and I still have that problem.

**Comment by andreyorst** [comment]
what version is it?

**Comment by andreyorst** [comment]
> Im using Kakoune v2019.01.20 on Linux Mint

This is previous stable release of Kakoune which did not include module sysyem. Current stable version is https://github.com/mawww/kakoune/releases/tag/v2019.07.01

**Comment by andreyorst** [comment]
> Could this be because im using zsh for the shell?

You should not link `zsh` to your `sh` binary, b2cause it will break many scripts that require POSIX complaint shell in `sh` binary, and `zsh` isn't exactly compatible with some of POSIX shell syntaxes. I suggest you to set your `$KAKOUNE_POSIX_SHELL` to `dash`. This way you can ensure that all scripts for Kakoune will work correctly regardless of what shell you're using or what is linked to your `sh` binary. This is general suggestion and not related to the issue with modules.

**Comment by Narven** [comment]
> > Im using Kakoune v2019.01.20 on Linux Mint
> 
> This is previous stable release of Kakoune which did not include module sysyem. Current stable version is https://github.com/mawww/kakoune/releases/tag/v2019.07.01

Yes, that is correct. The version that I had of Kakoune was not the latest. I was using linuxbrew to install Kakoune and that does not have the latest.

Had to install from source and now it works. Thanks
