### ISSUE TITLE
Add a plug-doc command

### ISSUE THREAD

**Issue by Delapouite** [andreyorst/plug.kak#70]
Hello

Almost all plugins that I know of have a `README.md` file at their root.

So what about a `plug-doc` command, that would have the all the installed plugins as auto-completion and would automatically opens the associated `README.md` ?

Example:
```
:plug-doc<space>
```

I select `ul/kak-lsp` for instance, then press `Enter`, Kakoune opens kak-lsp's `README.md`

### Bonus:

When the list of plugins is displayed in the `*plug*` buffer after a `:plug-list`, pressing a key like `d` would automatically call `plug-doc` for the plugin on the line.

**Comment by andreyorst** [comment]
Nice idea. Also, can be tied with a `doc` switch for `plug` command to specify documentation files or directory to parse and provide a list of files if there's more than one found as completion elements.

This way plugin authors can create `doc` directory and put a real documentation files there.

```
plug "ul/kak-lsp" doc %{
    doc/
    README.md
} config %{
    ...
}
```
What do you think?

**Comment by Delapouite** [comment]
Yes, your suggestion would be useful for plugins with bigger documentation.

Also I thought of an even better integration:
Instead of having a dedicated `plug-doc` command, could it be possible to hijack the regular `doc` command? (with `-override` or something)
The autocompletion would continue work as usual suggesting normal topics ('options', 'registers'…) but it will also add the name of plugins to displays their README.

This way the user would not have to learn something new, and this would be a pleasant surprise when they use the normal `doc` command and find that they can learn more about their favorite plugins.

**Comment by andreyorst** [comment]
I've thought about this, back when I've opened https://github.com/mawww/kakoune/issues/2402, but unfortunately we're still at a sad state of documenting features in terms of external plugins.

I think that when user executes `doc` command, the expected result is to see documentation. Kakoune uses asciidoc for documentation. Most plugins have markdown documentation (if any) and by overriding `doc` we make the assumption that opened file will fulfill the purpose as documentation.

Such feature should be handled with care. I think that when no `doc` folder in plugin is found and a `README` is used as documentation, we should at least warn user that this may not be actual  documentation.
