### ISSUE TITLE
Use %val{config} ?

### ISSUE THREAD

**Issue by Delapouite** [andreyorst/plug.kak#8]
The current default path is `'$HOME/.config/kak/plugins'`.

Should the plugin use something like `%val{config}/plugins` for better flexibility and cross-platform compatibility?

**Comment by andreyorst** [comment]
I've been thinking about it too, since when I've started to work on this manager, I didn't really knew about this variable. I'll change it

**Comment by andreyorst** [comment]
Fixed in #12
