### ISSUE TITLE
Stray lock file is preventing plug.kak from performing actions

### ISSUE THREAD

**Issue by raiguard** [andreyorst/plug.kak#81]
I have been having a blast tinkering with Kakoune, with no small thanks to you for this awesome plugin manager. However, at some point yesterday, something went wrong, because I can no longer install, clean, or update plugins:

![image](https://user-images.githubusercontent.com/3515394/111387491-68a5f600-8673-11eb-862c-458302ffa0f5.png)

This message appears every time, and never disappears. I have tried re-installing plug.kak from scratch twice, but that didn't help anything. This happens even if I reduce my kakrc to just the plug invocations.

Grepping over the source code led me to believe that it places this lock file in the plugins directory, but no such file exists there.

**Comment by andreyorst** [comment]
>
> Grepping over the source code led me to believe that it places this lock
> file in the plugins directory, but no such file exists there.
>
Hi! Lock-files are hidden, can you confirm that running `ls -la` in the
plugin installation directory shows no hidden lock-files?

**Comment by raiguard** [comment]
Ah, my apologies. I tried removing `.plug.kak.lock` instead of `.global.plug.kak.lock`. Thanks for the quick reply!

I'm still fairly inexperienced with command lines in general, so I had assumed that `ls` showed hidden files by default.

**Comment by andreyorst** [comment]
No worries! With Kakoune you'll be good in no time
