### ISSUE TITLE
Check for URL scheme when searching for an URL in the plguin name

### ISSUE THREAD

**Issue by mralusw** [andreyorst/plug.kak#85]
The pattern in [rc/plug.sh](https://github.com/andreyorst/plug.kak/blob/master/rc/plug.sh#L167) line 167 (`(http*|git*)`)is confusing. Is it *designed* to allow `git@github.com:...`, as a plugin developer might use, or is that just coincidental to the fact that there's no check for a URL scheme (`://`)?

Anyway, I've opened #84 to allow file:// URL schemes. Thanks for this very useful plugin!

**Comment by andreyorst** [comment]
> Is it designed to allow git@github.com:..., as a plugin developer might use

Yes

**Comment by mralusw** [comment]
Well, the current check also breaks for github repos who have the misfortune of being named `git-guru/kakplug`, `httpclient/kakadapter` etc.

**Comment by andreyorst** [comment]
well, that's just an oversight

**Comment by mralusw** [comment]
If you whitelist URL schemes (`*://*` in the case statement), that would solve many problems and future-proof the code. Also, `git` supports [`ext::` remotes](https://www.git-scm.com/docs/git-remote-ext).

**Comment by andreyorst** [comment]
> If you whitelist URL schemes (`*://*` in the case statement), that would solve many problems and future-proof the code.

I don't want to make it too generic, and I don't think we'll really need all that variety, as it was pretty long since anything else than `https?` and `git` was requested, so I'd rather add that feature when needed. 

> Also, `git` supports [`ext::` remotes](https://www.git-scm.com/docs/git-remote-ext).

This looks interesting, I'll add it.
