### ISSUE TITLE
demand doesn't work without a final %{}

### ISSUE THREAD

**Issue by mralusw** [andreyorst/plug.kak#89]
```
plug plugin demand mod %{}
```
works, but if the final %{} is removed, the plugin is silently ignored. It is listed as up-to-date, but its code is not sourced. For example any options declared in the plugin are unavailable, and any module declared in the plugin cannot be `require-module`'d.

**Comment by andreyorst** [comment]
@mralusw could you test the `fix-demand` branch please?

**Comment by mralusw** [comment]
Yes, it seems to work. Sorry for the delay and thank you.
