### ISSUE TITLE
Plugin status breaks if reflog empty

### ISSUE THREAD

**Issue by mralusw** [andreyorst/plug.kak#90]
In `plug.sh` / `plug_list`, the code checks for `@{0}`, which causes `git` to fail if the reflog is empty (can be triggered manually with `git reflog expire`, but probably can also happen automatically). Furthermore, `plug_list` interprets this failure as "Updates available".

Is there any reason to use `@{0}` instead of `@` (the actual `HEAD`)? If yes, the code could still be fixed by changing to
```
LOCAL=$(git rev-parse '@{0}') || LOCAL=$(git rev-parse '@')
```
(and similarly for `BASE=`)

My use case is that I compact all `kak` (and `vim`) plugins by deleting tags, reflogs, inactive remote branches, setting `git remote set-branches` to only the current branch, and running `git fsck` to repack only reachable objects. Some people put images (or even videos!) in their repository, so the space savings can be quite substantial, as long as only a minimal set of objects are reachable.

**Comment by andreyorst** [comment]
I don't do this kind of thing to my repos, so if you already do it, and you can test it properly, I would gladly accept a PR with such change. As for `@{0}` I, honestly, don't remember why I've used it. It's quite an old part of the plugin, and maybe something else can be used, I'm not a Git Guru :)

**Comment by mralusw** [comment]
I've looked and plug doesn't seem to be using (or designed to use) the reflog history. I'm not really sure if there's ever a difference, but if there is, it would be quite surprising to ignore the HEAD (and use the last reflog entry) for updating.

So, #92 switches to using `@` (normal HEAD). Minimal changeset.

**Comment by mralusw** [comment]
... as for my compacting tips, maybe *sometime* we can add a `plug-compact` command, or something in the docs. Include git shallowing too, like [`minpac`](https://github.com/k-takata/minpac) does.

But that is completely separate.
