### ISSUE TITLE
defer block not works as expected

### ISSUE THREAD

**Issue by TuM0xA-S** [andreyorst/plug.kak#94]
i have configuration for fzf.kak(Kakoune v2020.09.01)
```
plug "andreyorst/fzf.kak" %{
    map global normal \' ': fzf-mode<ret>'  # works
} defer fzf %{
    set-option global fzf_file_command fd # not works
}

```
### expected: 
option `fzf_file_command` have value `fd`
### actual:
option `fzf_file_command` not setted and have default value `find`
![problem](https://user-images.githubusercontent.com/64231066/124377818-b55f1c80-dcb6-11eb-8712-8e39787b5595.png)
also if set option after kakoune loaded it works.
am i doing something wrong?

**Comment by andreyorst** [comment]
because `fzf_file_command` is in `fzf-file` module, not in `fzf` module.

```
plug "andreyorst/fzf.kak" %{
    map global normal \' ': fzf-mode<ret>'  # works
} defer fzf-file %{
    set-option global fzf_file_command fd # not works
}
```

**Comment by TuM0xA-S** [comment]
thx
